SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND FROM BBA$ 
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND  FROM BCA$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND  FROM BCOM#AF$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND FROM BCOM#CS$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND FROM BCOM#G$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND  FROM CHE$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND FROM CS$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND FROM MTH$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND  FROM PHY$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND  FROM PSY$
UNION ALL
SELECT ADMISSION_NO, DEGREE, STUDENT_BRANCH, RELIGION, COMMUNITY, FATHER_INCOME, FATHER_OCCUPATION, FIRST_GEN_LEARNER, COURSE, BOARD, BACKGROUND  FROM BA$
order by 3